version: 0.2
phases: 
  install: 
    runtime-versions: 
      nodejs: 14

  pre_build: 
    commands: 
      - npm --versions
      - echo Installing NPM dependencies..; npm ci;
      - echo Auditing NPM dependencies..; npm audit;
      - echo Log in to Code Artifact..; npm run artifact:login:ci;

  build: 
    commands: 
      - echo Building dist; npm run build

  post_build: 
    commands: 
      - npm publish; 